name: Springer Lab Research
description: Science updates on maize epigenetics, genetics and genomcis from the Springer lab at University of Minnesota
url: https://maizeumn.github.io

markdown: kramdown
permalink: /:categories/:title/
future: true

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "*.tiff"
  - "*.xml"
  - "Gemfile"
  - "Gemfile.lock"

projects:
  - trvrb/coaltrace
  - trvrb/stem
  - trvrb/PACT
  - trvrb/dynamics-practical
  - trvrb/antigen
  - trvrb/haplotypes
  - trvrb/divergence
  - trvrb/ancestry
  - trvrb/medium-data
  - trvrb/flutrace
  - blab/nextflu
  - alvason/infectious-pulse
  - blab/global-migration
  - trvrb/sismid
  - trvrb/sctrace
  - trvrb/phylodynamics-lecture
  - blab/baltic
  - blab/chikv
  - blab/yellow-fever
  - blab/unsampled
  - nextstrain/fauna
  - nextstrain/augur
  - nextstrain/auspice
  - nextstrain/janus
  - nextstrain/sacra
  - blab/zika-seq
  - blab/siv-cst
  - blab/zika-usvi
  - blab/mitii
  - blab/mers-structure
